### ISSUE TITLE
Indexing is broken in elasticsearch-sink

### ISSUE THREAD

**Issue by klinamen** [spring-cloud/stream-applications#136]
It is the case elasticsearch-sink does not index documents properly on Elasticsearch as it sends the wrong HTTP request on the wire for messages with String or Map payloads.
For instance, the message with String payload `{"name": "John Doe", "age": 33}` is sent over the wire in the request body as `{"{\"name\": \"John Doe\", \"age\": 33}": "JSON"}`, causing disastrous effects.

Pull request #135 contains failing test cases and a proposed solution.

**Comment by sobychacko** [comment]
Addressed through https://github.com/spring-cloud/stream-applications/commit/7df5cc49712f01f89e9fa90e3548369ce7a75801.
