### ISSUE TITLE
Adding batch indexing to elasticsearch-sink

### ISSUE THREAD

**Issue by klinamen** [spring-cloud/stream-applications#138]
Elasticsearch sink should support batch indexing (sync and async) through ES bulk APIs.
PR #137 provides an implementation of this feature along the lines of jdbc-consumer.

**Comment by sabbyanandan** [comment]
Thanks, @klinamen. @sobychacko will have a look soon.

**Comment by sobychacko** [comment]
Addressed through the PR mentioned above.
