### ISSUE TITLE
BUG: sftp-sink does not enforce "app.sftp.use-temporary-filename=false"

### ISSUE THREAD

**Issue by izenkov** [spring-cloud/stream-applications#145]
The SFTP server file system I am working with does not support 'rename' functionality, therefore I have to set app.sftp.use-temporary-filename=false. Unfortunately after deployment sftp-sink still writes xxx.tmp file and fails trying to rename it.

app.sftp.allow-unknown-keys=true
app.sftp.auto-create-dir=false
app.sftp.filename-expression='scdf.txt'
app.sftp.host=<sftp-host>
app.sftp.mode=REPLACE
app.sftp.password=<userpassword>
app.sftp.use-temporary-filename=false
app.sftp.username=<username>

**Comment by artembilan** [comment]
The property must be `sftp.consumer.use-temporary-filename`. Although it is not clear what version of `sftp-sink` you are using...

**Comment by izenkov** [comment]
I am using latest 'Getting started': https://dataflow.spring.io/docs/installation/local/docker/

Environment variables:
DATAFLOW_VERSION='2.7.1'
SKIPPER_VERSION='2.6.1'

**Steps to reproduce:**

- docker-compose up
- Open UI: 'http://localhost:9393/dashboard"
- In UI create a stream: time | sftp
- In UI Publish stream 
- In UI Set sftp properties
- In UI: copy properties ('Copy to Clipboard' button)

*** cut clipboard ***
```
app.sftp.allow-unknown-keys=true
app.sftp.auto-create-dir=false
app.sftp.filename-expression='test.txt'
app.sftp.host=XXXX
app.sftp.mode=REPLACE
app.sftp.password=XXXX
app.sftp.use-temporary-filename=false
app.sftp.username=XXXX
```
*** cut clipboard ***

- Deploy stream

**Expected:**

File 'test.txt' uploaded to SFTP server

**Actual:**

File 'test.txt.tmp' uploaded to SFTP server
Also sftp-sink exception:

`2021-02-02 23:57:58.879 ERROR 135 --- [container-0-C-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageDeliveryException: Error handling message for file [String payload -> test.txt]; nested exception is org.springframework.messaging.MessagingException: Failed to write to '/test.txt.tmp' while uploading the file`

**Comment by izenkov** [comment]
According to SCDF Dashboard sftp sink is version 3.0.0
![sftp-sink-ver](https://user-images.githubusercontent.com/2333723/106680688-3dac8a80-657c-11eb-944d-020ac5fe88fa.jpg)

**Comment by artembilan** [comment]
OK. One more time: does it work if you add `consumer` prefix?
```
app.sftp.consumer.allow-unknown-keys=true
app.sftp.consumer.auto-create-dir=false
app.sftp.consumer.filename-expression='test.txt'
app.sftp.consumer.host=XXXX
app.sftp.consumer.mode=REPLACE
app.sftp.consumer.password=XXXX
app.sftp.consumer.use-temporary-filename=false
app.sftp.consumer.username=XXXX
```

I wonder from where did you get those options and they come without `consumer` prefix...
See docs for the sink version: https://github.com/spring-cloud/stream-applications/tree/master/applications/sink/sftp-sink

**Comment by izenkov** [comment]
> OK. One more time: does it work if you add consumer prefix?
Pardon my ignorance, but how can I add the prefix from UI?
![sftp-properties](https://user-images.githubusercontent.com/2333723/106682838-967e2200-6580-11eb-8759-646df8919344.png)

**Comment by izenkov** [comment]
To get the options into clipboard is easy, Just push this button ;-)
![copy-to-clipboard](https://user-images.githubusercontent.com/2333723/106683990-ce866480-6582-11eb-8feb-de6949789b13.png)

**Comment by artembilan** [comment]
You were right. 

That property has just not been propagated to the target SFTP Outbound Channel Adapter!

The DataFlow UI confused me though...

Sorry for delay: after looking into the code it became fully clear that the bug has a place.

It would be great if you are able to test you solution against `3.0.1-SNAPSHOT`.

Thank you for your patience!

**Comment by izenkov** [comment]
Thank you for a prompt response.
I will be happy to verify the fix!

**Comment by izenkov** [comment]
Trying to build https://github.com/spring-cloud/stream-applications.git master HEAD but getting test errors. Appreciate any clues on how to validate the fix...

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.83 s <<< FAILURE! - in org.springframework.cloud.fn.common.cdc.CdcBootStarterIntegrationTest
[ERROR] org.springframework.cloud.fn.common.cdc.CdcBootStarterIntegrationTest  Time elapsed: 0.83 s  <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=debezium/example-mysql:1.0, imagePullPolicy=DefaultPullPolicy())
Caused by: com.github.dockerjava.api.exception.NotFoundException: 
Status 404: {"message":"No such image: testcontainers/ryuk:0.3.0"}

**Comment by izenkov** [comment]
I was able to build it:

./mvnw -e clean install -P bootstrap -Dmaven.javadoc.skip=true verify -DskipTests

**Comment by artembilan** [comment]
Why do you need to build it, if you just could check your solution against snapshot?

**Comment by izenkov** [comment]
Because I am new to SCDF ;-) And I did not know that I can just do:

`app register --name sftp-new --type sink --uri maven://org.springframework.cloud.stream.app:sftp-sink-kafka:3.0.1-SNAPSHOT`

Anyway, I just tested 3.0.1-SNAPSHOT and it works as expected.
Thank you for promptly fixing it!
