### ISSUE TITLE
sftp Should Differentiate Between filenamePattern and filenameRegex

### ISSUE THREAD

**Issue by fiidim** [spring-cloud/stream-applications#146]
Current code appears to be agnostic between filenamePattern and filenameRegex, as both are treated as Regex patterns (`SftpRegexPatternFileListFilter`).  filenamePattern previously worked as:

`item_*.dat`

Is now required to be like a regex:

`item_.*\.dat`

If they are both handled the same by pattern filter, they should only be a single parameter.  Also, might be noteworthy in the migration path to 3.0.0 versions of application starter.

**Comment by artembilan** [comment]
This is copy/paste bug:

```
if (StringUtils.hasText(sftpSupplierProperties.getFilenamePattern())) {
	chainFilter
			.addFilter(new SftpRegexPatternFileListFilter(sftpSupplierProperties.getFilenamePattern()));
}
else if (sftpSupplierProperties.getFilenameRegex() != null) {
	chainFilter
			.addFilter(new SftpRegexPatternFileListFilter(sftpSupplierProperties.getFilenameRegex()));
}
```

Of course the first one must be a `SftpSimplePatternFileListFilter`.

Will be fixed soon.

Thank you for the report!
