### ISSUE TITLE
Add the possibilities to configure the headersMappedLast for the RabbitMQ consumer

### ISSUE THREAD

**Issue by nithril** [spring-cloud/stream-applications#152]
Hello,

The RabbitMQ consumer is using by default a `org.springframework.amqp.support.converter.SimpleMessageConverter` that is setting the content type when `headersMappedLast` is set to false (default).

It means when the payload is of type `byte[]` the content type will be set to `application/octet-stream` whereas in most case it should remain unchanged: RabbitMQ is in most of the case a passthrough medium. In a scenario involving 2 streams connected by a queue, with 1 RabbitMQ sink and 1 RabbitMQ source, it can create issue as the app next to the source is receiving `application/octet-stream` and not the right `application/json`. 

Please let me know if it makes sense, I can then submit a PR.

Nicolas

**Comment by artembilan** [comment]
Yes, it makes sense. 

And probably you are right: it must be `true` by default since in most cases we really just rely received `byte[]` from the binder to this RabbitMQ sink.

Please, go ahead with PR and we will review it shortly.

Thank you!
