### ISSUE TITLE
Migrate tasklauncher sink to SCDF repo

### ISSUE THREAD

**Issue by dturanski** [spring-cloud/stream-applications#158]
tasklauncher sink is a special case since it depends on dataflow client, there is a risk that it may not work with incompatible dataflow server versions.  To address this, move the function and app components to the `spring-cloud-dataflow` repo and release with the SCDF.  Going forward, it will use the same version as SCDF and be published to the stream app repo, but not built by this project. 

Move the components and references  in the build. 
Add a README that the project has been moved and link to the new location.  
Should not be included in the bulk import.  Data flow will take care of the registration. 
Consider if we can reuse the app generation using the external repo.

Depends on https://github.com/spring-cloud/spring-cloud-dataflow/issues/4443

**Comment by sabbyanandan** [comment]
We will have to also think about the app registration workflow in SCDF. Maybe automatically register this app similar to CTR?

**Comment by sabbyanandan** [comment]
Based on the internal sync with @dturanski and @sobychacko, here's the decision and the next steps. 

1- Name the new module in SCDF repo as `tasklauncher` (retain `taskluancher-dataflow` for users who have this already in the registry and are using it)
2- Add a deprecation WARNING message to `taskluancher-dataflow` app, so folks know they need to switch over to the new app eventually.
3- Update `taskluancher-dataflow`'s README with the deprecation and the steps and instructions on how to register/use the `tasklauncher` app shipped in SCDF.
4- In SCDF, when bulk importing, intercept the POST, see if the POST has "rabbit" or "kafka" as the string literal, and automatically register and rabbit/kafka variant of the new `tasklauncher` app to the registry.
5- Retain `tasklauncher` with the same version as SCDF's and SCDF client's version. i.e: Don't start with 1.0.

**Comment by onobc** [comment]
This has been done for quite a while - closing as such
