### ISSUE TITLE
What's difference between Spring Cloud Stream Applications and Spring Cloud Stream App Starters

### ISSUE THREAD

**Issue by zhanyigo** [spring-cloud/stream-applications#163]
Hi,

I'm looking for a streaming sink to load data into Greenplum.  I found gpfdist-sink from Spring Cloud Stream App Starters project. And I can not find it in this project. 
What's difference between Spring Cloud Stream Applications and Spring Cloud Stream App Starters projects?

**Comment by sabbyanandan** [comment]
Spring Cloud Stream App Starters repo includes apps that are built with older and legacy versions of Spring Cloud Stream and the Spring Cloud stack. 

The newer architecture where the applications are function-based is hosted under this repo (stream-applications), where you can flexibly iterate, patch, and mix-match with other business functions more easily. 

You can read more about the new apps and the why's from the [release blog](https://spring.io/blog/2020/12/21/announcing-spring-cloud-stream-applications-2020-0-0-ga-release).
