### ISSUE TITLE
MongoDB Consumer README

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/stream-applications#17]
As a developer, I would like to reuse the MongoDB Consumer bean as a standalone component in my application. I would like to go through a quick README that explains how this consumer can be injected in my application.

Ideally, this README should be provided as part of the mongodb-consumer module.

**Comment by artembilan** [comment]
Fixed via https://github.com/spring-cloud/stream-applications/commit/a712c40705bd5a62e641ef13421133362dfeeab7
