### ISSUE TITLE
Prepare for 2021.0.0 SNAPSHOT

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/stream-applications#171]
- [x] Upgrade to Boot 2.5 (via cloud / build)
- [x] Upgrade to Stream 3.1
- [x] Document new apps/function
- [x] Prepare a bulk-import link of 2021.0.0 SNAPSHOTs
- [x] Migrate zeromq apps from 3.1-WIP branch
- [x] 3 tests in [SftpSupplierApplicationTests](https://github.com/spring-cloud/stream-applications/blob/main/functions/supplier/sftp-supplier/src/test/java/org/springframework/cloud/fn/supplier/sftp/SftpSupplierApplicationTests.java) are failing - @dturanski  or @artembilan could you please take a look?
- [x] Some tests in Websocket supplier/source are failing - @artembilan do you have some cycles to look into this?
- [x] This Security test is [disabled](https://github.com/spring-cloud/stream-applications/blob/main/applications/stream-applications-core/stream-applications-security-common/src/test/java/org/springframework/cloud/stream/app/security/common/SecurityEnabledManagementSecurityEnabledTests.java#L53). @artembilan do you recognize anything there?
- [x] Same as above [here](https://github.com/spring-cloud/stream-applications/blob/main/applications/stream-applications-core/stream-applications-security-common/src/test/java/org/springframework/cloud/stream/app/security/common/ReactiveSecurityEnabledManagementSecurityEnabledTests.java#L54) cc @artembilan 
- [x] This time-source [test](https://github.com/spring-cloud/stream-applications/blob/main/applications/source/time-source/src/test/java/org/springframework/cloud/stream/app/source/time/TimeSourceTests.java#L84) is failing. For some reason, the binding is interpreted as `output.destination`. @dturanski Could you take a look?
- [x] Few [tests](https://github.com/spring-cloud/stream-applications/blob/main/applications/processor/http-request-processor/src/test/java/org/springframework/cloud/stream/app/processor/http/request/HttpRequestProcessorTests.java) are disabled for HTTP Request Processor. @dturanski Could you take a look?
- [x] Twitter trend location tests are [disabled](https://github.com/spring-cloud/stream-applications/blob/main/applications/processor/twitter-trend-processor/src/test/java/org/springframework/cloud/stream/app/processor/twitter/trend/TwitterTrendLocationProcessorIntegrationTests.java#L61). @tzolov Could you pls take a look?
- [x] Cloudfoundry/Micrometer tags tests are [disabled](https://github.com/spring-cloud/stream-applications/blob/main/applications/stream-applications-core/stream-applications-micrometer-common/src/test/java/org/springframework/cloud/stream/app/micrometer/common/CloudFoundryMicrometerCommonTagsTest.java). @tzolov Could you look into them to see what's wrong with the upgrades?
- [x] aggregator processor docs are giving some issues. [Disabled](https://github.com/spring-cloud/stream-applications/blob/main/applications/processor/aggregator-processor/pom.xml#L27) the docs plugin for aggregator processor apps. @dturanski Do you recognize anything?
- [x] CDC Debezium [test](https://github.com/spring-cloud/stream-applications/blob/main/functions/common/cdc-debezium-boot-starter/src/test/java/org/springframework/cloud/fn/common/cdc/CdcBootStarterIntegrationTest.java#L46) failures - @tzolov when running with `-Pintegration`, there are test failures on the CDC Supplier/source. Tests are disabled now. 
- [x] All Redis consumer [tests](https://github.com/spring-cloud/stream-applications/blob/main/functions/consumer/redis-consumer/src/test/java/org/springframework/cloud/fn/consumer/redis/RedisConsumerKeyTests.java#L39) are failing currently and are disabled.

**Comment by artembilan** [comment]
What is dead line please?

**Comment by sobychacko** [comment]
@artembilan Please take your time. I was thinking to put a milestone by mid-July, so we have some time.
