### ISSUE TITLE
http-request url is always giving 403 forbidden error though works with postman

### ISSUE THREAD

**Issue by maulikdoshi82** [spring-cloud/stream-applications#181]
Using Spring Cloud Data Flow - 
file --directory=/home/cnb/scdf --filename-pattern=*.txt --mode=lines | http-request --url-expression=payload --expected-response-type=byte[] --maximum-buffer-size=2097152  | log --level=INFO

File has only one content:
http://www.google.com/

Running it throws 403 - Forbidden error. 

Tried to add headres as below:
file --directory=/home/cnb/scdf --filename-pattern=*.txt --mode=lines | http-request --url-expression=payload --expected-response-type=byte[] --maximum-buffer-size=2097152 --headers-expression={'User-Agent':'Mozilla/5.0','Accept':'*/*','accept-encoding':'gzip, deflate'} | log --level=INFO but still the same error.

**Comment by artembilan** [comment]
The `http-request` function has this logic by default:
```
private Object resolveBody(Message<?> message) {
	return properties.getBodyExpression() != null ? properties.getBodyExpression().getValue(message)
				: message.getPayload();
}
```
So, if you don't provide an explicit `body-expression`, the actual message payload is used anyway.
Technically what you show is translated to the: `curl -X GET -d "http://www.google.com/" http://www.google.com/`
And with this I got error like `org.springframework.web.reactive.function.client.WebClientResponseException$BadRequest: 400 Bad Request from GET http://www.google.com/)`.
Not sure how you have reached `403 - Forbidden`, but testing your stream against Google was not perfect idea from the beginning...

We probably need to reconsider that `body-expression` defaults, e.g. do not insert it if method is not `PUT` or `POST` and this expression is not configured explicitly.
But there is nothing we can help at the moment if you stick with GET against that google.com.

Thanks for understanding!

**Comment by maulikdoshi82** [comment]
Hi @artembilan <

 thank you for the response and the pointer to getBodyExpression. Setting it to empty string for now has solved the issue.

**Comment by artembilan** [comment]
That’s interesting … I tried with `body-expression=null`, but failed in the `WebClient` request preparation that it cannot be `null`.

I didn’t think that empty string would be the way for Google to ignore request body. Will debug tomorrow : probably WebFlux just doesn’t set target HTTP request body if it is an empty string…
