### ISSUE TITLE
Router-sink dead link in README.adoc

### ISSUE THREAD

**Issue by fiidim** [spring-cloud/stream-applications#191]
In the SpEL-based routing section of the [README.adoc](https://github.com/spring-cloud/stream-applications/blob/main/applications/sink/router-sink/README.adoc) for router-sink, the link for "Configuration (Generic) Router section" is dead.   

I believe you either want:
[Configuring a Generic Router](https://docs.spring.io/spring-integration/reference/html/router.html#router-namespace)
or
[Routers and the Spring Expression Language (SpEL)](https://docs.spring.io/spring-integration/reference/html/router.html#router-spel)

since [Configuring (Generic) Router section](https://docs.spring.io/spring-integration/reference/html/messaging-routing-chapter.html#router-namespace) doesn't exist

**Comment by artembilan** [comment]
I think this link is correct: https://docs.spring.io/spring-integration/reference/html/router.html#router-namespace.

If you won't mind, please, consider to raise a simple PR to fix the problem and we will merge it shortly.

Thank you!
