### ISSUE TITLE
How to add or adjust the configuration of the file supplier?

### ISSUE THREAD

**Issue by erizzo** [spring-cloud/stream-applications#195]
Spring Cloud Stream's file-supplier dependency includes `FileSupplierConfiguration` which configures a File message source (from Spring Integration). I need to customize the `FileReadingMessageSource` that this @Configuration provides, but I'm not sure of the best way to do so. It provided only basic properties to control its @Beans, but I need more.

I considered excluding `FileSupplierConfiguration` from the app, but I'd then have to copy most of the code from it into my own @Confguration class. Obviously that's a less than ideal solution. It also doesn't seem to work in Spring Boot, which complains that `FileSupplierConfiguration` is not a known config when I try to exclude it.

So how can I customize the File message source, for example with additional FileListFilters?

This is a cross-post of [a StackOverflow question](https://stackoverflow.com/q/69442462/639520).

**Comment by erizzo** [comment]
> Feel free to re-open if you are still having issues with this.

I don't appear to have the ability to re-open this issue.

**Comment by artembilan** [comment]
> But that seems like a bug that would have been discovered long ago, right?

That's right. I'll look into this tomorrow.

Thank you for your persistence and patience!

Reopenig the issue since your concern is correct.

I believe we need to come up with something like `MessageSourceCustomizer<S extends MessageSource<?>>` and similar for other functions and consumers.

**Comment by artembilan** [comment]
See similar request: https://stackoverflow.com/questions/69802199/how-to-use-watchservicedirectoryscanner-with-spring-cloud-stream-file-supplier
