### ISSUE TITLE
Example of using Kafka

### ISSUE THREAD

**Issue by code-magician323** [spring-cloud/stream-applications#202]
I've couldn't manage to find any example of using Kafka here and I wonder what is the reason for this. Any usage of Kafka with spring cloud stream as a source would be great. It also very unclear why isn't there's an option of using Kafka source and sink with Spring Cloud Data Flow

**Comment by code-magician323** [comment]
Any new?

**Comment by suneel-p** [comment]
Sir please provide an example for how we sending this captured data to kafka topic

**Comment by sobychacko** [comment]
It is not clear what the question is. Could you please elaborate and describe where/what type of issues you are facing?

**Comment by suneel-p** [comment]
Im asking for debezium sends data to kafka topic and from there consuming data from topic and send to target db.please if you provide like that it will be more helpfull for me.thank you

**Comment by zt1983811** [comment]
Yes, I would like to ask the exactly the same question, from the application I can see there is rabbitMQ as source and sink,
 but I can't find anything for kafka.
What I would like to do simply is read from one topic from kafka then write to another topic of kafka.

![image](https://user-images.githubusercontent.com/2559543/158916339-f60fa009-09ee-40c7-8354-802e79ce3296.png)

**Comment by onobc** [comment]
This is now tracked via https://github.com/spring-cloud/stream-applications/issues/265
