### ISSUE TITLE
Ability to add external libs to generated apps

### ISSUE THREAD

**Issue by onobc** [spring-cloud/stream-applications#236]
### What / Why
Once the sample apps are generated and published there is no mechanism for users to add more dependencies. One recent example is [here](https://stackoverflow.com/questions/71037448/how-to-use-elk-with-scdf-stream-applications).

To extend the dependencies the user must currently do the following:
- clone the stream-applications repo locally
- add the dependency in the app's pom.xml
- build and publish the app

In order to avoid the above steps, it would be nice if there was a mechanism to let users configuratively add more dependencies.

### How
Leverage Spring Boot [ProperiesLauncher](https://docs.spring.io/spring-boot/docs/current/reference/html/executable-jar.html#executable-jar.property-launcher) jar format which supports the ability to add external dependencies via the `loader.path` property / `LOADER_PATH` env var. 

#### Concerns
- [ ] Requires move from JarLauncher to PropertiesLauncher, we need to understand the tradeoffs
  - does this format cause issues w/ native?
  - does this format result in bigger jars? 
  - etc..

**Comment by Hassen-BENNOUR** [comment]
Hi folks,
Yep i'm facing this work and think that is a very good idea to avoid these steps :)
Thanks!

**Comment by making** [comment]
I think adding extra libs and setting `LOADER_PATH` would be acceptable for the local development but quite painful for k8s platforms and probably impossible for cf platforms.

For k8s, creating a custom docker image would be the realistic solution.
Here is my Dockerfile example (s3-source-kafka + mongodb metadata store) how to add extra libs to the existing without cloning the stream-applications repo locally:

```dockerfile
FROM maven as deps
RUN echo -e '<?xml version="1.0" encoding="UTF-8"?>\n\
<project xmlns="http://maven.apache.org/POM/4.0.0"\n\
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n\
     xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">\n\
  <modelVersion>4.0.0</modelVersion>\n\
  <parent>\n\
    <groupId>org.springframework.boot</groupId>\n\
    <artifactId>spring-boot-starter-parent</artifactId>\n\
    <version>2.6.3</version>\n\
    <relativePath/>\n\
  </parent>\n\
  <groupId>com.example</groupId>\n\
  <artifactId>deps</artifactId>\n\
  <version>0.0.1-SNAPSHOT</version>\n\
  <name>deps</name>\n\
  <description>deps</description>\n\
  <dependencies>\n\
    <dependency>\n\
      <groupId>org.springframework.boot</groupId>\n\
      <artifactId>spring-boot-starter-data-mongodb</artifactId>\n\
    </dependency>\n\
    <dependency>\n\
      <groupId>org.springframework.integration</groupId>\n\
      <artifactId>spring-integration-mongodb</artifactId>\n\
    </dependency>\n\
  </dependencies>\n\
</project>'\
>> /tmp/pom.xml
RUN mvn -X -f /tmp/pom.xml dependency:copy-dependencies -DoutputDirectory=/libs

FROM springcloudstream/s3-source-kafka:3.2.0
COPY --from=deps /libs/*.jar /app/libs/
```

It looks like it's working well.

**Comment by corneil** [comment]
This PR may help [https://github.com/spring-cloud/spring-cloud-dataflow/pull/5044](https://github.com/spring-cloud/spring-cloud-dataflow/pull/5044)

**Comment by onobc** [comment]
The approach has been added in SCDF (PR above) but the docs are not surfaced anywhere in the stream-apps docs. 
This still needs to be done.

**Comment by corneil** [comment]
https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#extend-classpath
