### ISSUE TITLE
Reduce integration test log output

### ISSUE THREAD

**Issue by onobc** [spring-cloud/stream-applications#243]
Running the integration tests produces copious amounts of debug logs to the console. It would be nice to reduce the logging when running the tests. 

The TwitterTests have been identified as one culprit. There are probably more. 

Run the tests w/ to observe the output. 
```
./mvnw clean install -Pintegration
```

**Comment by dturanski** [comment]
Actually, testcontainers sets logging to DEBUG by default. Twitter and others are affected. I'm working my way through some of these.

**Comment by onobc** [comment]
@dturanski this is done, correct?

**Comment by dturanski** [comment]
Yes
________________________________
