### ISSUE TITLE
Can't infer the SQL type to use for an instance of io.debezium.data.SpecialValueDecimal

### ISSUE THREAD

**Issue by nadeem4** [spring-cloud/stream-applications#253]
I am using Postgres version 12, and I am performing incremental snapshot but I am getting `Can't infer the SQL type to use for an instance of io.debezium.data.SpecialValueDecimal. Use setObject() with an explicit Types value to specify the type to use.` It is already fixed by Debezium in 1.8 version and later.

Is there any temporary fix until `cdc-debezium-common` is upgraded with latest debezium version.

**Comment by onobc** [comment]
Hi @nadeem4 ,

> Is there any temporary fix until cdc-debezium-common is upgraded with latest debezium version.

We will get Debezium upgraded in the next release. However, to help find a workaround I need to understand the underlying issue that is fixed in `1.8+`. Can you share the schema for one of the failing tables? Is the [key numeric](https://issues.redhat.com/browse/DBZ-4298)?

**Comment by tzolov** [comment]
Solved with the new debezium autoconfiguration, supplier and source apps. 
Incremental Snapshot is tested with MySQL, SQL Server and Postgres databases.
