### ISSUE TITLE
Project reactor support

### ISSUE THREAD

**Issue by ipanimnim** [spring-cloud/stream-applications#254]
Is there any support for reactor in this repo? I think its important to be able to plug and play reactor components within Spring Cloud Dataflow

**Comment by artembilan** [comment]
What are those reactor components are you talking about? If you open functions in this project, you’ll see that they deal with `Flux` and `Mono` this or other way. Why is there a concern that Reactor has to be on top of visibility? Why it is just not enough that applications of this project does their logic in reactive manner? Why do you want to hear reactive support , but not a particular problem solution? Technically you must not care about details of the component, but just build a required logic via Data Flow.

**Comment by sobychacko** [comment]
@ipanimnim Closing the issue based on the comment from @artembilan. Feel free to re-open if you have more use cases or context.
