### ISSUE TITLE
Spring Cloud DataFlow Docker S3 Source not working as expected

### ISSUE THREAD

**Issue by Noushath** [spring-cloud/stream-applications#258]
Hi Team
I am creating an scdf(Spring Cloud DataFlow) pipeline from **scdf jar on local mac** with below config using s3 as source and destination as kafka topic:

s3 --auto-create-local-dir=false --local-dir=/tmp --supplier.filename-regex='.*\.csv$'  --cloud.aws.region.auto=false --cloud.aws.credentials.profileName=default --cloud.aws.region.static=**us-east-2** --remote-dir=**xxxxx** --file.consumer.mode=lines --cloud.aws.stack.auto=false > :someKafkaRawTopic

The bucket xxxx belongs to us-east-2 as highlighted in stream definition above , but sadly getting below exception:

_org.springframework.messaging.MessagingException: Problem occurred while synchronizing 'bucket' to local directory; nested exception is org.springframework.messaging.MessagingException: Failed to execute on session; nested exception is com.amazonaws.services.s3.model.AmazonS3Exception: The bucket is in this region: us-east-1. Please use this region to retry the request_

But if we use buckets from us-east-1 and point same in definition it works. 
Is this s3 connector only supposed to be working for us-east-1 region buckets? 

Also when running from **scdf docker we are not able to pass the credentials to access s3 and we get access denied even though we are able to exec into scdf container and run aws s3 commands, this access denied error gets thrown even for us-east-1 buckets which are working fine from scdf jar with same above config. Does the stream definition need to be different when running from docker strangely !!!**.

Request if some one can guide on how the stream definition should look like for s3 source when running from scdf docker image.

Also we would like to run this stream in AWS EKS, so please throw some light on how to pass AWS credentials from EKS node instance role

**Comment by artembilan** [comment]
The first error is something expected according S3 protocol:
```
    } catch (AmazonS3Exception ase) {
            /**
             * This is to handle the edge case: when the bucket is deleted and recreated in a different region,
             * the cache still has the old region info.
             * If region is not specified, the first request to this newly created bucket will fail because it used
             * the outdated region present in cache. Here we update the cache with correct region. The subsequent
             * requests will succeed.
             * The recommended practice for any request is to provide region info always.
             */
            if (ase.getStatusCode() == 301) {
                if (ase.getAdditionalDetails() != null) {
                    String region = ase.getAdditionalDetails().get(Headers.S3_BUCKET_REGION);
                    bucketRegionCache.put(bucket, region);
                    ase.setErrorMessage("The bucket is in this region: " + region +
                                        ". Please use this region to retry the request");
                }
            }
            throw ase;
        } finally {
```

See `AmazonS3Client.invoke()`.

The second one (and probably third as well) is more about how you configure credentials for this application.
Perhaps it is better to consider to use a `cloud.aws.credentials.use-default-aws-credentials-chain = true` instead of that `cloud.aws.credentials.profileName=default`...

Anyway this looks more like AWS support ticket, or at least Spring Cloud AWS request rather than what we can control over here with these applications.

**Comment by Noushath** [comment]
> The first error is something expected according S3 protocol:
> 
> ```
>     } catch (AmazonS3Exception ase) {
>             /**
>              * This is to handle the edge case: when the bucket is deleted and recreated in a different region,
>              * the cache still has the old region info.
>              * If region is not specified, the first request to this newly created bucket will fail because it used
>              * the outdated region present in cache. Here we update the cache with correct region. The subsequent
>              * requests will succeed.
>              * The recommended practice for any request is to provide region info always.
>              */
>             if (ase.getStatusCode() == 301) {
>                 if (ase.getAdditionalDetails() != null) {
>                     String region = ase.getAdditionalDetails().get(Headers.S3_BUCKET_REGION);
>                     bucketRegionCache.put(bucket, region);
>                     ase.setErrorMessage("The bucket is in this region: " + region +
>                                         ". Please use this region to retry the request");
>                 }
>             }
>             throw ase;
>         } finally {
> ```
> 
> See `AmazonS3Client.invoke()`.
> 
> The second one (and probably third as well) is more about how you configure credentials for this application. Perhaps it is better to consider to use a `cloud.aws.credentials.use-default-aws-credentials-chain = true` instead of that `cloud.aws.credentials.profileName=default`...
> 
> Anyway this looks more like AWS support ticket, or at least Spring Cloud AWS request rather than what we can control over here with these applications.

Yes I had taken this query https://github.com/awspring/spring-cloud-aws/discussions/319 with spring cloud aws but looks like they asked to check it here

**Comment by artembilan** [comment]
Check this unit test: https://github.com/spring-cloud/stream-applications/blob/main/applications/source/s3-source/src/test/java/org/springframework/cloud/stream/app/source/s3/AwsS3SourceTests.java

**Comment by Noushath** [comment]
> cloud.aws.credentials.use-default-aws-credentials-chain = true

This is the stream definition used in eks which fails with access denied even though the k8s node has the required roles

s3 --auto-create-local-dir=false --local-dir="/tmp" --supplier.filename-regex=".*\.csv$" --cloud.aws.region.auto=false --cloud.aws.region.static=us-east-1 --remote-dir=xxxxx --file.consumer.mode=lines --cloud.aws.stack.auto=false --cloud.aws.credentials.use-default-aws-credentials-chain=true > :scdfRawTopic

**Comment by artembilan** [comment]
I still think that credentials concern is out of our control.
See here: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html and consider to consult with AWS what kind of credentials provider they provide on that EKS.

**Comment by sobychacko** [comment]
@Noushath Any updates or further context to this issue? Can we close this issue now?

**Comment by Noushath** [comment]
> @Noushath Any updates or further context to this issue? Can we close this issue now?

We figured out there is an issue with the s3 source connector properties editor which is trimming the property key for bucket name
s3 --auto-create-local-dir=false --local-dir="/tmp" --supplier.filename-regex=".*.csv$" --cloud.aws.region.auto=false --cloud.aws.region.static=us-east-1 --**remote-dir**=xxxxx --file.consumer.mode=lines --cloud.aws.stack.auto=false --cloud.aws.credentials.use-default-aws-credentials-chain=true > :scdfRawTopic

When we added the prefix s3 correctly to remote-dir property it started working. Someone has to fix the issue in spring cloud dataflow s3 source properties, as we spend good amount of time not able to figure out if it was the bucket and permissions and lately we came to know the bucket name was not getting passed correctly as prefix was getting dropped.
Try creating a sample stream and before deploying open the editor and provide the bucket name and we will end up in same error as we got that needs to be corrected.

s3 --auto-create-local-dir=false --local-dir="/tmp" --supplier.filename-regex=".*.csv$" --cloud.aws.region.auto=false --cloud.aws.region.static=us-east-1 --**s3.remote-dir**=xxxxx --file.consumer.mode=lines --cloud.aws.stack.auto=false --cloud.aws.credentials.use-default-aws-credentials-chain=true > :scdfRawTopic

**Comment by artembilan** [comment]
@Noushath ,

thank you for confirmation that the problem has gotten a fix on your side!

>Someone has to fix the issue in spring cloud dataflow s3 source properties

Tell us, please, more about this and we will see what and how we can fix from the framework side.

**Comment by artembilan** [comment]
OK. I see your concern:
This one doesn't work for you, `--remote-dir=xxxxx`, but this one does ` --s3.remote-dir=xxxxx`.

This is something with Spring Cloud DataFlow and its ability to read and rely on the metadata, which is like this for this `s3-source`:
```
configuration-properties.classes=org.springframework.cloud.fn.supplier.s3.AwsS3SupplierProperties,\
  org.springframework.cloud.fn.common.file.FileConsumerProperties,\
  org.springframework.cloud.fn.common.aws.s3.AmazonS3Properties, \
  org.springframework.cloud.fn.common.metadata.store.MetadataStoreProperties, \
  org.springframework.cloud.fn.common.metadata.store.MetadataStoreProperties$Gemfire, \
  org.springframework.cloud.fn.common.metadata.store.MetadataStoreProperties$Redis, \
  org.springframework.cloud.fn.common.metadata.store.MetadataStoreProperties$DynamoDb, \
  org.springframework.cloud.fn.common.metadata.store.MetadataStoreProperties$Jdbc, \
  org.springframework.cloud.fn.common.metadata.store.MetadataStoreProperties$Zookeeper, \
  org.springframework.cloud.fn.common.metadata.store.MetadataStoreProperties$Mongo
```

Where that `remote-dir` is a part of the first configuration properties file:
```
@ConfigurationProperties("s3.supplier")
@Validated
public class AwsS3SupplierProperties {

	/**
	 * AWS S3 bucket resource.
	 */
	private String remoteDir = "bucket";
```

So, everything has to be OK and even that `s3.remote-dir` is wrong since it has to be like `s3.supplier.remote-dir`.

Therefore my conclusion that something is wrong with your DataFlow instance.

Closing this over here as nothing to fix from the S3 Source perspective.

Feel free to reopen in the https://github.com/spring-cloud/spring-cloud-dataflow

Thanks again!
