### ISSUE TITLE
Update the OpenJDK image

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/stream-applications#259]
Investigate what needs to be updated [here](https://github.com/spring-cloud/baseimage/blame/main/Dockerfile). 

Ensure that the proper versions are aligned and used in the new apps.

**Comment by sobychacko** [comment]
The plugins might need some changes related to this. https://github.com/spring-cloud/spring-cloud-dataflow-apps-plugin

**Comment by corneil** [comment]
> The plugins might need some changes related to this. https://github.com/spring-cloud/spring-cloud-dataflow-apps-plugin

@sobychacko 
Not sure there are any changes needed based on `spring-cloud-dataflow-apps-plugin`

The `Dockerfile` is using:
Liberica `11.0.8+10` and latest is `11.0.15+10`

It is using Ubuntu Bionic (18.04 LTS) we could safely go to Ubuntu Focal (20.04 LTS)

Why are we using Ubuntu and not Alpine image to reduce the size?

**Comment by onobc** [comment]
> One enhancement we can make is to map a folder to `/extra` and configure `LOADER_PATH=/extra` in `Dockerfile` so that it is easy to add JDBC drivers or other jars without creating own image.

Yep, this is similar to the approach outlined in the corresponding ticket. I would prefer to keep that effort in the scope of #236.

**Comment by corneil** [comment]
Before release changes required to `applications/stream-applications-core/pom.xml` so the version of the plugin is new release.

```
<spring-cloud-dataflow-apps-generator-plugin.version>1.0.7-SNAPSHOT</spring-cloud-dataflow-apps-generator-plugin.version>
<spring-cloud-dataflow-apps-docs-plugin.version>1.0.7-SNAPSHOT</spring-cloud-dataflow-apps-docs-plugin.version>
<spring-cloud-dataflow-apps-metadata-plugin.version>1.0.7-SNAPSHOT</spring-cloud-dataflow-apps-metadata-plugin.version>
```
