### ISSUE TITLE
Consider combining apps generator plugin with stream-applications

### ISSUE THREAD

**Issue by onobc** [spring-cloud/stream-applications#263]
- The only consumer of the apps plugin is stream-applications
- If we do this, it will be w/ the next major version (SB3)

**Comment by onobc** [comment]
SCDF does in fact use the plugin https://github.com/spring-cloud/spring-cloud-dataflow/blob/7620eea20f321fdb37345be65f0f1a870aa59f8b/pom.xml#L342

**Comment by fiidim** [comment]
For the record, I also use the app generator as part of my stream application suite. It’s useful enough as a standalone plugin. I’d hate to have to clone it if I don’t need to.

**Comment by onobc** [comment]
Hi @fiidim , 

Are you modifying the plugin or just using it as an imported dependency? If we combine with the stream-applications repo we would still publish the plugin at the same maven coordinates.

**Comment by tzolov** [comment]
Resolved at 4e554423946d7d4ac8a4056cdd55eac3e17f37eb
