### ISSUE TITLE
Add Kafka source and sink apps

### ISSUE THREAD

**Issue by onobc** [spring-cloud/stream-applications#265]
To complete parity w/ the Rabbit source / sink, lets add a Kafka source/sink app. 

Motivation: https://github.com/spring-cloud/stream-applications/issues/202

**Comment by Zishnu** [comment]
Please add the external kafka source and sink requirements as in enterprise application sceneries. The source and target application would be writing messages to external broker which is different from message broker topic.

**Comment by artembilan** [comment]
Reopened for Supplier and Source implementation part.

**Comment by fengnv17** [comment]
> Reopened for Supplier and Source implementation part.
could you tell the date for kafka supplier? thanks.

**Comment by artembilan** [comment]
> could you tell the date for kafka supplier? thanks.

I'm looking into that these days.
So, we may have a SNAPSHOT for `kafka-supplier`  next week.
If you are asking about GA release, then ti might be something like a month yet.
