### ISSUE TITLE
Update mail-source/sink apps to use Greenmail

### ISSUE THREAD

**Issue by onobc** [spring-cloud/stream-applications#270]
This is removed already in Spring Integration `6.0` in favor of GreenMail library: https://github.com/greenmail-mail-test/greenmail.
I don't say to revise and fix this immediately, but need to be ready for consequences 😄

_Originally posted by @artembilan in https://github.com/spring-cloud/stream-applications/pull/269#discussion_r878322064_

**Comment by onobc** [comment]
The following locations need to be switched to use Greenmail:

- mail-source/src/test/java/org/springframework/cloud/stream/app/source/file
- test/java/org/springframework/cloud/fn/supplier/mail

**Comment by artembilan** [comment]
Some Spring Integration usage of Greenmail: https://github.com/spring-projects/spring-integration/blob/main/spring-integration-mail/src/test/java/org/springframework/integration/mail/dsl/MailTests.java

**Comment by corneil** [comment]
Updated mail-supplier and mail-source tests to use GreenMail.
