### ISSUE TITLE
Script processor app not able to pass non ascii characters from payload in pipeline

### ISSUE THREAD

**Issue by Noushath** [spring-cloud/stream-applications#312]
Hi Team,
Below is the stream definition we have:

SPECIAL-CHAR-TEST-1=web-app: http --server.port=8383 --http.path-pattern='/testapi' | set-header: header-enricher --headers='content-type=application/json; charset=utf-8' | **processed: script --script='function run(p) {p = json.PARSE(p); p.updated = true; return p;} run(payload)' --language=javascript** > :processed-record

After the payload goes through script processor we are getting **?** for non ascii chars
sample request to our pipeline is as below:
curl --location --request POST 'http://localhost:8383/testapi' --header 'Content-Type: application/json' --data-raw '{ "name": "**Ангеліна**"}'

So as highlighted in name above with non ascii char get transformed to below:
<img width="221" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/100141346/179202972-80407920-ffe7-4ba0-b2f6-836dc2acfa3f.png">

Need some help on how to set up script processor to handle such records, please we are using **javascript** as language for script processor.

**Comment by artembilan** [comment]
How does it look, please, if you add charset to the `curl` command:
```
curl --location --request POST 'http://localhost:8383/testapi' --header 'Content-Type: application/json; charset=utf-8' --data-raw '{ "name": "Ангеліна"}'
```
?

**Comment by Noushath** [comment]
> How does it look, please, if you add charset to the `curl` command:
> 
> ```
> curl --location --request POST 'http://localhost:8383/testapi' --header 'Content-Type: application/json; charset=utf-8' --data-raw '{ "name": "Ангеліна"}'
> ```
> 
> ?

No it doesn't seem working with charset=utf-8 in http source ,as mentioned earlier problem is with script processor app.

**Comment by onobc** [comment]
Hi @Noushath 

A few questions for you:

**Q1**: What are you using to view the output? 

**Q2**: What do you see if you change your stream definition to the following? 
```
SPECIAL-CHAR-TEST-1=web-app: http --server.port=8383 --http.path-pattern='/testapi'  > :processed-record
```
**Q3**: Are you using `spring-cloud-dataflow`?

**Comment by Noushath** [comment]
> Hi @Noushath
> 
> A few questions for you:
> 
> **Q1**: What are you using to view the output?
> 
> **Q2**: What do you see if you change your stream definition to the following?
> 
> ```
> SPECIAL-CHAR-TEST-1=web-app: http --server.port=8383 --http.path-pattern='/testapi'  > :processed-record
> ```
> 
> **Q3**: Are you using `spring-cloud-dataflow`?

Yes we are using spring cloud dataflow.
There is no problem upto the last kafka topic from http source , only when its processed in script its messed up, if you try above definition and consume from the destination topic you will be able to see the problem

**Comment by onobc** [comment]
> **Q1:** What are you using to view the output?

Can you answer this for me please? 

> There is no problem upto the last kafka topic from http source 

Were you able to change your definition to what I suggested above in **Q2** and use the same mechanism to view the output on the destination topic and you saw it come back w/ the non-standard chars? 

> only when its processed in script its messed up, if you try above definition and consume from the destination topic you will be able to see the problem

I have not been able to reproduce the issue yet. I see the proper output coming out of the script processor. 

I do have a couple of questions about the script def though:
1. the header enricher fails for me complaining about the `;` (I had to adjust it a bit)
2. I had to use `JSON.parse` rather than `json.PARSE`
3. 
I am wondering why you are not also seeing these issues.

**Comment by Noushath** [comment]
> > **Q1:** What are you using to view the output?
> 
> Can you answer this for me please?
> 
> > There is no problem upto the last kafka topic from http source
> 
> Were you able to change your definition to what I suggested above in **Q2** and use the same mechanism to view the output on the destination topic and you saw it come back w/ the non-standard chars?
> 
> > only when its processed in script its messed up, if you try above definition and consume from the destination topic you will be able to see the problem
> 
> I have not been able to reproduce the issue yet. I see the proper output coming out of the script processor.
> 
> I do have a couple of questions about the script def though:
> 
> 1. the header enricher fails for me complaining about the `;` (I had to adjust it a bit)
> 2. I had to use `JSON.parse` rather than `json.PARSE`
> 
> I am wondering why you are not also seeing these issues.

please share the definition you have used will try same and see if we are getting the issue or not?

**Comment by onobc** [comment]
> We are using kafka conumers to read from destination topic.

Are you certain the data is stored in the topic is not encoded properly and it is not the display of the tool that is reading the value actually garbling the output? This has happened to me before that is why I am asking. This is why I was asking to remove the script processor from the stream def and be certain you can view the encoded data properly using the same mechanism you are using to view the data currently. 


> I do have a couple of questions about the script def though:
> 
> the header enricher fails for me complaining about the ; (I had to adjust it a bit)
> I had to use JSON.parse rather than json.PARSE

- Did you not see any issues (errors in app log on script processor) around this at runtime? 
- Are you creating the def via the UI or command line (REST or shell)?

> Also you are trying with nonascii characters right like what I mention in sample above?

Yep

> please share the definition you have used will try same and see if we are getting the issue or not?

I will try to get this to you shortly.

**Comment by onobc** [comment]
Hi @Noushath, 

The definition I am using is below. You will notice I replaced `> :processed-record` w/ `| log` to rule out any issues w/ viewing data in Kafka. 
```java
http --server.port=8383 --http.path-pattern='/testapi' | header-enricher --headers=content-type='application/json; charset=utf-8' | script --language=javascript --script='function run(p) {p = JSON.parse(p); p.updated = true; return p;} run(payload)' | log
```

Here is the `cURL` I am using to exercise it:
```java
curl --location --request POST 'http://localhost:8383/testapi' --header 'Content-Type: application/json' --data-raw '{ "name": "Ангеліна"}'
```

Here is the result in the `log` sink's application log:
```java
2022-07-26 13:11:45.753  INFO [log-sink,2f0a8f3cddf2a109,936e40b722c43882] 16026 --- [container-0-C-1] log-sink                                 : {"name":"Ангеліна","updated":true}
```

**Comment by Noushath** [comment]
> Hi @Noushath,
> 
> The definition I am using is below. You will notice I replaced `> :processed-record` w/ `| log` to rule out any issues w/ viewing data in Kafka.
> 
> ```java
> http --server.port=8383 --http.path-pattern='/testapi' | header-enricher --headers=content-type='application/json; charset=utf-8' | script --language=javascript --script='function run(p) {p = JSON.parse(p); p.updated = true; return p;} run(payload)' | log
> ```
> 
> Here is the `cURL` I am using to exercise it:
> 
> ```java
> curl --location --request POST 'http://localhost:8383/testapi' --header 'Content-Type: application/json' --data-raw '{ "name": "Ангеліна"}'
> ```
> 
> Here is the result in the `log` sink's application log:
> 
> ```shell
> ....[container-0-C-1] log-sink                                 : {"name":"Ангеліна","updated":true}
> ```

We could see the problem was in the docker image locale for script processor, which was POSIX for script processor, specifying utf-8 to deployer properties in k8s text is displayed correctly in kafka consumer. Did you try above definition with maven jars or docker images of spring cloud dataflow stream apps.

**Comment by onobc** [comment]
Ahhh interesting @Noushath . I was using maven jars.

**Comment by onobc** [comment]
We do not set the locale on the docker image. 

I believe you can also set the required properties once (rather than on every deploy) via the `environmentVariables` in your k8s config. Something like: 
```
environmentVariables: 'LANG=en_US.UTF-8,LC_ALL=en_US.UTF-8'
```

In the meantime, I will open an improvement issue in Spring Cloud Dataflow to document our findings w/ workaround and also look into providing a property in SCDF to control this.
