### ISSUE TITLE
cdc-debezium has some questions about offset.

### ISSUE THREAD

**Issue by yuhuyuyu** [spring-cloud/stream-applications#319]
I created a stream in scdf using cdc-debezium.
![image](https://user-images.githubusercontent.com/67989582/176377169-963f5c6b-6a7b-404b-9a61-8c24c896668e.png)
Apparently a snapshot of the database was taken when cdc-debezium was initialized to get all datas.But when I undeploy the stream and then deploy the stream again, as expected, I thought it would start getting data from the position where it was interrupted last time.But I see the following information in the log.This was followed by another database snapshot.
```log
INFO [cdc-debezium-source,,] 1 --- [pool-1-thread-1] i.d.connector.common.BaseSourceTask      : No previous offsets found
...
INFO [cdc-debezium-source,,] 1 --- [pool-1-thread-1] i.d.c.p.connection.PostgresConnection    : Obtained valid replication slot ReplicationSlot [active=false, latestFlushedLsn=null, catalogXmin=null]
INFO [cdc-debezium-source,,] 1 --- [pool-1-thread-1] i.d.c.postgresql.PostgresConnectorTask   : No previous offset found
INFO [cdc-debezium-source,,] 1 --- [pool-1-thread-1] i.d.c.p.snapshot.InitialSnapshotter      : Taking initial snapshot for new datasource
```

Then I saw the following configuration in [spring.io](https://docs.spring.io/spring-cloud-stream-app-starters/docs/Einstein.SR6/reference/htmlsingle/#_options_23).
![image](https://user-images.githubusercontent.com/67989582/176380703-2f08a7ee-a866-442f-ad8d-02a4027068aa.png)
So I added the following configuration
```
cdc.offset.storage=kafka
```
I thought this would solve the problem, but I found other problems in the log.Apparently an error occurred during deploy this time.
```log
ERROR [cdc-debezium-source,,] 1 --- [pool-1-thread-1] o.s.cloud.fn.common.cdc.EmbeddedEngine   : Unable to configure and start the 'org.apache.kafka.connect.storage.KafkaOffsetBackingStore' offset backing store
org.apache.kafka.common.config.ConfigException: Offset storage topic must be specified
    at org.apache.kafka.connect.storage.KafkaOffsetBackingStore.configure(KafkaOffsetBackingStore.java:84) ~[connect-runtime-3.0.0.jar:na]
    at org.springframework.cloud.fn.common.cdc.EmbeddedEngine.run(EmbeddedEngine.java:728) ~[cdc-debezium-common-1.2.0.jar:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
    at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```
I'm curious to know how I should configure it correctly so that cdc-debezium continues where it left off when redeploying, instead of taking a database snapshot every time?

**Comment by markpollack** [comment]
thanks for reporting this, we will prioritize looking into this issue.  Not sure off the top of my head what is going on, though the whole CDC implementation should be shifting over to newer features in debezium, e.g. https://github.com/spring-cloud/stream-applications/issues/188

**Comment by onobc** [comment]
Hi @yuhuyuyu ,

You are looking at the correct configuration area but please use the [latest docs here](https://github.com/spring-cloud/stream-applications/blob/main/applications/source/cdc-debezium-source/README.adoc#cdcoffset). I will make sure we update the links in spring.io on our end to avoid directing users to stale docs. 

Either way, the docs are missing how to configure the particular offset stores. 

For `kafka`, we need to add the `cdc.offset.storage.topic` name of topic to store offsets to. It may require more configuration options but I am not sure. I would love to find out the exact settings myself and share w/ you but will not be able to get to that for 1-2 days. If you want to give this a try now and lmk what you find that could possibly get you quicker results. 

The other options would need this additional config as well:

* `file` -> `cdc.offset.storage.file.filename`
* `metadata` -> props depend on what SI metadata store you would choose to use

Thanks

**Comment by onobc** [comment]
I create these follow on issues:
- https://github.com/spring-cloud/stream-applications/issues/320
- https://github.com/spring-cloud/stream-applications/issues/321

**Comment by tzolov** [comment]
Hi @yuhuyuyu, here is an important correction to the previous answer! 

Currently the Spring CDC Source doesn't expose shortcut for the connector offset configurations (e.g `cdc.offset.storage.topic` doesn't exist)!

But you can use the `cdc.config.` prefix to set directly any native Debezium or Kafka Connect properties!  

In your case of configuring that Kafka Offset Store you can set the following properties:
- `cdc.config.offset.storage.topic` -  The name of the Kafka topic where connector offsets are stored.
- `cdc.config.offset.storage.partitions` -  The number of partitions used when creating the offset storage topic.
-  `cdc.config.offset.storage.replication.factor` - Replication factor used when creating the offset storage topic.

Please let me know if this solved your issue. 

(P.S. In addition to connect's native `kafka`, `file` and `memory` offset stores, the Spring CDC Source adds support for all [SI Metadata Stores](Metadata Store) as well! )

**Comment by yuhuyuyu** [comment]
Hi @tzolov ,thank you very much for your reply and help.This configuration successfully solved the problem I encountered.
Just add the following configuration.
- `cdc.config.bootstraap.servers`
