### ISSUE TITLE
Null default values in generated docs

### ISSUE THREAD

**Issue by onobc** [spring-cloud/stream-applications#346]
@artembilan I already merged this. We will follow up though to understand why the default is now null.

_Originally posted by @onobc in https://github.com/spring-cloud/stream-applications/pull/345#discussion_r990171324_

**Comment by corneil** [comment]
I did notice some of the docs were regenerated by the local build running abd that it had removed the geode references. There may be something else it required in a pom that we removed.

**Comment by onobc** [comment]
There was something off w/ the repo/deps at the time of these initial PRs. Looks like back in 2021-10-17 we re-ran the build which updated/fixed all of these invalid default values https://github.com/spring-cloud/stream-applications/commit/7f5ea9260ecd5453c481268476b1071f753f2bb5

I verified this by stepping through debugger on the apps-doc-plugin during stream-applications build and saw the proper defaults being written to the README.adoc.
