### ISSUE TITLE
ElasticSearch high level client removed in SB3 

### ISSUE THREAD

**Issue by onobc** [spring-cloud/stream-applications#367]
We need to use the new ElasticSearch Java client instead (see [SB release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M4-Release-Notes#elasticsearch-clients-and-templates)).

In the meantime, the ES related tests have been `@Disabled` - reenable once this is fixed.

**Comment by corneil** [comment]
Implemented
