### ISSUE TITLE
`object-detection-function` tests do not run on M1 macbook pro

### ISSUE THREAD

**Issue by dmfrey** [spring-cloud/stream-applications#401]
There's an open issue on the dependent project to provide support for the protoc-3.7.0-osx-aarch_64.exe:

https://github.com/os72/protoc-jar/issues/93

```
[ERROR] Failed to execute goal com.github.os72:protoc-jar-maven-plugin:3.7.0:run (default) on project object-detection-function: Error extracting protoc for version 3.7.0: Unsupported platform: protoc-3.7.0-osx-aarch_64.exe -> [Help 1]
```

**Comment by corneil** [comment]
@dmfrey  The dependencies have been updated with the latest snapshot. Please check if they make any difference.

**Comment by onobc** [comment]
Failed w/ something else...

```java
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:50 min
[INFO] Finished at: 2023-01-12T16:00:21-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.os72:protoc-jar-maven-plugin:3.11.4:run (default) on project object-detection-function: Error extracting protoc for version 3.11.4: Unsupported platform: protoc-3.11.4-osx-aarch_64.exe -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

**Comment by corneil** [comment]
Found that I can add `<protocArtifact>com.google.protobuf:protoc:${protobuf.version}</protocArtifact>` to the configuration of protoc-jar-maven-plugin and it will download the official build of protoc from Maven. 
Try newer versions if you experience issues. The `protobuf-java` and `protoc` versions should be the same.

**Comment by onobc** [comment]
This now works locally on M1 - thanks @corneil .

Closing via 722fb9182a6422c49bed3ff15c938ee61a4c692b
