### ISSUE TITLE
Unable to use S3-Source for polling a folder inside a bucket

### ISSUE THREAD

**Issue by mvenu-mbo** [spring-cloud/stream-applications#431]
I'm trying to create a stream which needs to listen to a folder in S3 bucket.

I could create a stream listening to the root of the bucket using following properties and could trigger the process.

app.s3-in.s3.supplier.remote-dir=mybucket
app.s3-in.filename-pattern=*.csv
app.s3-in.cloud.aws.credentials.accessKey=XXXXXXXXXX
app.s3-in.cloud.aws.credentials.secretKey=YYYYYYYYYYYYYYYYY
app.s3-in.cloud.aws.region.static=ZZZZZZZZ
app.s3-in.cloud.aws.stack.auto=false

But unable to listen to a folder in the bucket. I tried with following options:

app.s3-in.s3.supplier.remote-dir=mybucket/myfolder
app.s3-in.s3.supplier.remote-dir=mybucket/myfolder/
app.s3-in.s3.supplier.remote-dir=/mybucket/myfolder
app.s3-in.s3.supplier.remote-dir=/mybucket/myfolder/

I tried setting app.s3-in.path-style-access=true as well with above 4 options.

I tried changing remote-dir property to remoteDir as well.
I don't see any error message in the scdf server log.

we are using following versions:
rabbitmq server: 3.11.5
scdf server: 2.9.4
skipper server: 2.8.6

**Comment by artembilan** [comment]
The `path-style-access` does make sense (end used) only if `s3.common.endpoint-url` for S3 compatible storage, but it is not used for standard AWS S3: https://github.com/spring-cloud/stream-applications/tree/main/applications/source/s3-source.
Doesn't look like it has to do anything with your request anyway:
```
    /**
     * <p>Configures the client to use path-style access for all requests.</p>
     *
     * <p>Amazon S3 supports virtual-hosted-style and path-style access in all Regions. The
     * path-style syntax, however, requires that you use the region-specific endpoint when
     * attempting to access a bucket.</p>
     *
     * <p> The default behaviour is to detect which access style to use based on the configured
     * endpoint (an IP will result in path-style access) and the bucket being accessed (some buckets
     * are not valid DNS names). Setting this flag will result in path-style access being used for
     * all requests.</p>
     *
     * @param pathStyleAccessEnabled True to always use path-style access.
     * @return This object for method chaining.
     */
    public Subclass withPathStyleAccessEnabled(Boolean pathStyleAccessEnabled) {
```

There is no `sub-dir` concept in the S3 protocol. 
Whatever you see as a `sub-dir` is an artificial, logical distinction of one entry from another.
Essentially that `sub-dir` i a part of S3 object key.
Therefore you indeed have to configure only as `app.s3-in.s3.supplier.remote-dir=mybucket` and deal with those `myfolder/myfile.csv` on your own downstream.
The S3 is a key-value store: I'm not sure why people are so confused to look at it as a file system...

**Comment by mvenu-mbo** [comment]
Yes, I understand that there is no `sub-dir` concept in S3, but I expect that the downstream should receive a message with file name same as key name i.e. `myfolder/myfile.csv`. The downstream is not receiving any message when file is placed.

**Comment by artembilan** [comment]
I think you are contradicting to your own original question:

> I could create a stream listening to the root of the bucket using following properties and could trigger the process.

Which you claim for the `app.s3-in.s3.supplier.remote-dir=mybucket` configuration.
And that's exactly what I suggest to do. No any of those `myfolder`-based configs are correct.

You can turn on a `DEBUG` logging level for the `org.springframework.integration` category to see what is going on with that S3 Source when it connects and tries to pull data from the bucket.

**Comment by mvenu-mbo** [comment]
I got it @artembilan
I'm able to see a message being passed from S3 source to the next component in the stream when my key name is myfile.csv (i.e. placing directly in the root of the bucket).
My point is when I place a key for example, `myfolder/myfile.csv`, I'm expecting a message to be passed to the downstream with file name in the message header as `myfolder/myfile.csv`, which is missing in the next component in the stream.
I'll try the with DEBUG level logging.
Thanks for your time @artembilan

**Comment by artembilan** [comment]
OK. After some testing I see that current S3 Source does not support complex keys: all the resources has to be stored in the root.
It does create sub-dirs in local one, but it does not scan down to them.
A `RecursiveDirectoryScanner` must be provided, but we don't expose such an option on S3 Source yet.

Stay tuned.

**Comment by artembilan** [comment]
Let's see if this workaround help you!
```
		@Bean
		ComponentCustomizer<S3InboundFileSynchronizingMessageSource> s3SourceComponentCustomizer() {
			return component -> {
				component.setScanner(new RecursiveDirectoryScanner());
				component.setLocalFilter(new AbstractFileListFilter<>() {

					@Override
					public boolean accept(File file) {
						return !file.isDirectory();
					}

				});
			};
		}
```
