### ISSUE TITLE
[Docs] Improve docs around stream apps table

### ISSUE THREAD

**Issue by onobc** [spring-cloud/stream-applications#477]
## Duplication
There is a table that lists the available stream apps and it is in multiple locations:

- **This repo README:** https://github.com/spring-cloud/stream-applications/blob/main/README.adoc#reusable-spring-cloud-stream-applications
- **SCDF Microsite:** https://dataflow.spring.io/docs/applications/pre-packaged/#scdf-stream-applications
- **Spring Project Page:** https://spring.io/projects/spring-cloud-stream-applications#overview

This duplication leads to inconsistency across locations and is toil to attempt to keep the table up-to-date.
- [ ] An improvement would be to manage this table in a single location - and link to (or use) the central table.
- [ ] A further improvement would be to auto-generate the central table.

## Formatting
In addition to the duplication, the table layout is currently confusing. There is a 3 column table (source, processor, sink). Each column is alpha-ordered but there is also an attempt to line up rows that have representation in more than 1 column (eg. `xmpp`, `twitter`, etc..). 
It may be less confusing to instead break the 3 column table into 3 separate lists (one for `source, processor, sink`) and just make them alpha-ordered. 

> [!NOTE]
> The [spring-functions-catalog](https://github.com/spring-cloud/spring-functions-catalog?tab=readme-ov-file#reusable-functions) is already using this single column format.

**Comment by onobc** [comment]
> Indeed such a file could be generated: I believe I can write some Gradle task simply based on Groovy File API, but I don't think it would be possible with Maven without custom plugin or so...

I was thinking the same thing. Even w/o the auto-generation, the other 2 points would be a big improvement.

**Comment by onobc** [comment]
- Solved the duplication by making the table in this repo's README the single source of truth and having the other locations simply link to the sample apps section in the README.

- Fixed the formatting in this repo's README.

- Not going to do any auto-generation of the table at this point.

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-cloud/stream-applications/commit/e4143370eb8d0f1c485088e685519056b68acba3
