### ISSUE TITLE
[rabbit-source-rabbit-3.2.1] Disabling the Tomcat causes the Spring Cloud Dataflow App to be stuck in `Deploying`

### ISSUE THREAD

**Issue by r-heimann** [spring-cloud/stream-applications#489]
**Description:**
Disabling the internal Tomcat of `rabbit-source-rabbit-3.2.1` causes the Spring Cloud Dataflow Stream to be stuck in `Deploying`. I'm not entirely sure if this is an issue of Rabbit-Source or Spring Cloud Dataflow.

**Release versions:**
spring-cloud-skipper-server-2.9.3.jar
spring-cloud-dataflow-server-2.10.3.jar
rabbit-source-rabbit-3.2.1.jar

**Steps to reproduce:**

1. Start spring-cloud-skipper-server-2.9.3.jar
2. Start spring-cloud-dataflow-server-2.10.3.jar
3. Create a Stream using rabbit-source-rabbit-3.2.1.jar as a Source
4. Disable the internal Tomcat using the Application Property `app.<RabbitSourceName>.spring.main.web-application-type=none`

**Comment by corneil** [comment]
The internal Tomcat is used to provide web endpoints. Spring Actuator uses web endpoints and the default configuration of dataflow uses actuator to determine the health, liveness and readiness state of applications.
