### ISSUE TITLE
Ensure functions are documented once

### ISSUE THREAD

**Issue by onobc** [spring-cloud/stream-applications#524]
Now that the functions have moved to spring-functions-catalog we need to update the function related documentation in each application as follows.

For each application, update the README.adoc by replacing the currently generated configuration properties w/ a link that points to its respective function configuration options.

As an example consider the  `file-sink` app and its usage of `spring-file-consumer` function. 

The [file-sink README](https://github.com/spring-cloud/stream-applications/tree/main/applications/sink/file-sink#optionshttps://github.com/spring-cloud/stream-applications/tree/main/applications/sink/file-sink#options) currently looks like:

<img width="706" alt="Screenshot 2024-03-18 at 09 41 08" src="https://github.com/spring-cloud/stream-applications/assets/28907971/b0502d9e-d6d6-444c-9150-45faf19f2289">

and the "Options" sections will instead simply be a link that points to the respective function catalog docs - https://github.com/spring-cloud/spring-functions-catalog/tree/main/consumer/spring-file-consumer#configuration-options in above example.

**Comment by artembilan** [comment]
I went ahead and cleaned READMEs in SFsC: https://github.com/spring-cloud/spring-functions-catalog/commit/77112eb8a1f66f0c9d11e7d6908bea6abb4f9db0

**Comment by onobc** [comment]
Closed via https://github.com/spring-cloud/stream-applications/commit/7487dc8f6161e8f3a10232fd4ebce8504e0fcd7f
