### ISSUE TITLE
redis-metadatastore for s3/ftp-source

### ISSUE THREAD

**Issue by borg1310** [spring-cloud/stream-applications#561]
hi,

I would like to use a redis metadatastore for the two applications ftp-source and s3-source so that identical files are not emitted multiple times, even if the system is restarted. Is there a way to use the redis metadatastore without having to rebuild and redeploy the two applications?

Thanks in advance

best regards,
juergen

**Comment by corneil** [comment]
You will have to make your own copies of those projects and add 

```xml
<dependency>
    <groupId>org.springframework.integration</groupId>
    <artifactId>spring-integration-redis</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-redis</artifactId>
</dependency>
```
as described here: https://github.com/spring-cloud/spring-functions-catalog/tree/main/common/spring-metadata-store-common

**Comment by borg1310** [comment]
ok, thanks a lot
