### ISSUE TITLE
S3 sink and source don't work together in a SCDF stream

### ISSUE THREAD

**Issue by tsalm-pivotal** [spring-cloud/stream-applications#74]
The following stream example:
```
s3-source --s3.supplier.remote-dir=/quelle --s3.supplier.delete-remote-files=true --cloud.aws.credentials.accessKey=YOUR_ACCESS_KEY --cloud.aws.stack.auto=false --cloud.aws.credentials.secretKey=YOUR_SECRET_KEY --cloud.aws.region.static=eu-central-1 --JBP_CONFIG_SPRING_AUTO_RECONFIGURATION='{enabled: false}' --SPRING_PROFILES_ACTIVE=cloud | s3-sink --s3.consumer.bucket=/ziel --cloud.aws.credentials.accessKey=YOUR_ACCESS_KEY --cloud.aws.credentials.secretKey=YOUR_SECRET_KEY --cloud.aws.region.static=eu-central-1 --cloud.aws.stack.auto=false --JBP_CONFIG_SPRING_AUTO_RECONFIGURATION='{enabled: false}' --SPRING_PROFILES_ACTIVE=cloud
```

will result in the following error with all supported modes(contents, lines, ref) for an image file on SCDF with RabbitMQ:

`
org.springframework.messaging.MessageHandlingException: error occurred in message handler [bean 'amazonS3MessageHandler'; defined in: 'org.springframework.cloud.fn.consumer.s3.AwsS3ConsumerConfiguration'; from source: 'org.springframework.core.type.StandardMethodMetadata@598bd2ba']; nested exception is java.lang.IllegalArgumentException: Unsupported payload type: [class java.lang.String]. The only supported payloads for the upload request are java.io.File, java.io.InputStream, byte[] and PutObjectRequest., failedMessage=GenericMessage [payload=�PNG ..., headers={amqp_receivedDeliveryMode=PERSISTENT, amqp_receivedExchange=t-s3-4.s3-source-rabbit, amqp_deliveryTag=1, file_name=test.png, deliveryAttempt=3, amqp_consumerQueue=t-s3-4.s3-source-rabbit.t-s3-4, amqp_redelivered=false, file_originalFile=/home/vcap/tmp/s3-supplier/test.png, file_relativePath=test.png, amqp_receivedRoutingKey=t-s3-4.s3-source-rabbit, amqp_timestamp=Mon Jul 06 11:03:16 UTC 2020, amqp_messageId=04bcf6c2-cd2c-4d56-4772-9559da7738c8, id=e0d2f693-c753-5d7e-1563-07249b6ee546, amqp_consumerTag=amq.ctag-55gGyWTwemRbHEUqC5uysw, sourceData=(Body:'�PNG ...' MessageProperties [headers={file_name=test.png, file_originalFile=/home/vcap/tmp/s3-supplier/test.png, file_relativePath=test.png}, timestamp=Mon Jul 06 11:03:16 UTC 2020, messageId=04bcf6c2-cd2c-4d56-4772-9559da7738c8, contentType=application/json, contentLength=0, receivedDeliveryMode=PERSISTENT, priority=0, redelivered=false, receivedExchange=t-s3-4.s3-source-rabbit, receivedRoutingKey=t-s3-4.s3-source-rabbit, deliveryTag=1, consumerTag=amq.ctag-55gGyWTwemRbHEUqC5uysw, consumerQueue=t-s3-4.s3-source-rabbit.t-s3-4]), contentType=application/json, timestamp=1594033396095}]
`

**Comment by artembilan** [comment]
Hi @tsalm-pivotal !

After some private discussion with @sobychacko  we decide to look at this as a real issue.
We have some ideas how to improve it on the framework level (not sure yet `source` or `sink`), but there is definitely something has to be done around `contentType`.

Meanwhile let's if if function composition can help you.
See https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.6.RELEASE/reference/html/spring-cloud-stream.html#_functional_composition.

What I mean has to be something like this:
```
--spring.cloud.function.definition=spelFunction|s3Consumer
```
And for that `spelFunction` you need to provide this option:
```
--spel.function.expression='new java.io.File(payload)'
```

when you use a `ref` mode on the source side.

Probably something similar should be done for `contents` or `lines`:
```
--spel.function.expression='payload.bytes'
```

Let us know how is that!

**Comment by tsalm-pivotal** [comment]
I was not able to temporarily fix it with function composition or a processor `transform --expression='new java.io.File(payload)'`. It looks like the sink handles every payload as a string, but I was not able to reproduce this with a unit test.

**Comment by tsalm-pivotal** [comment]
FYI the "old" s3 source app starter sends the message with content-type application/octet-stream and the new with content-type application/json:
```
GenericMessage [payload=byte[66333], headers={file_originalFile=/home/vcap/tmp/s3-source/test.png, id=06351785-28aa-b2dd-d9d1-74eb702a2022, contentType=application/octet-stream, file_name=test.png, file_relativePath=test.png, timestamp=1594125370015}]
```
vs
```
GenericMessage [payload=byte[66333], headers={file_name=test.png, file_originalFile=/home/vcap/tmp/s3-supplier/test.png, id=ccea672f-4d4a-08f5-d04e-b423f8d63077, contentType=application/json, file_relativePath=test.png, timestamp=1594125382955, accept=application/json}]
```

**Comment by artembilan** [comment]
@sobychacko , 
we need to investigate what is going on on Spring Cloud Stream level.
According our source configuration we end up with the logic in the `FileUtils` which really populates for us a `contentType` header, e.g.:
```
case contents:
				flowBuilder.enrichHeaders(Collections.<String, Object>singletonMap(MessageHeaders.CONTENT_TYPE,
						MimeTypeUtils.APPLICATION_OCTET_STREAM_VALUE))
						.transform(new FileToByteArrayTransformer());
				break;
```

then we produce this bean:
```
@Bean
public Supplier<Flux<Message<?>>> s3Supplier() {
	return () -> Flux.from(s3SupplierFlow());
}
```
which is picked up by Spring Cloud Stream. And according @tsalm-pivotal  's report the proper content type is overridden back to `application/json`.

Thanks

**Comment by tsalm-pivotal** [comment]
As a workaround you can set `--outputType=application/octet-stream` for the s3 source:
``` 
s3-source --outputType=application/octet-stream --s3.supplier.remote-dir=/quelle --s3.supplier.delete-remote-files=true --cloud.aws.credentials.accessKey=YOUR_ACCESS_KEY --cloud.aws.stack.auto=false --cloud.aws.credentials.secretKey=YOUR_SECRET_KEY --cloud.aws.region.static=eu-central-1 --JBP_CONFIG_SPRING_AUTO_RECONFIGURATION='{enabled: false}' --SPRING_PROFILES_ACTIVE=cloud | s3-sink --s3.consumer.bucket=/ziel --cloud.aws.credentials.accessKey=YOUR_ACCESS_KEY --cloud.aws.credentials.secretKey=YOUR_SECRET_KEY --cloud.aws.region.static=eu-central-1 --cloud.aws.stack.auto=false --JBP_CONFIG_SPRING_AUTO_RECONFIGURATION='{enabled: false}' --SPRING_PROFILES_ACTIVE=cloud
```

**Comment by sobychacko** [comment]
I believe [this commit ](https://github.com/spring-cloud/spring-cloud-function/commit/0537ce061b34d4f2b9cac51c825cbb220156e8d5)in Spring Cloud Function addressed this issue. Closing the issue. Feel free to re-open if the fix is not sufficient enough.
