### ISSUE TITLE
Http source mapped-request-headers flag doesn't include the mapped header in the Message

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/stream-applications#77]
Http Source's output Message doesn't include the mapped request headers even after setting the flag `mapped-request-headers` on http source.

**Comment by artembilan** [comment]
Any chances to see a sample how to reproduce an issue?
There is indeed a configuration property like `http.mappedRequestHeaders`.

Thanks

**Comment by sobychacko** [comment]
Closing as this turned out to be a non-issue. cc/ @ilayaperumalg
